blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreatView, BlogUpdateView, BlogDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blogs/create/', BlogCreatView.as_view(), name='blog_create'),
    path('blogs/<int:pk>/update', BlogUpdateView.as_view(), name='update'),
    path('blogs/<int:pk>/delete', BlogDeleteView.as_view(), name='delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, reset_password, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(),name="logout"),
    path('register/', UserCreateView.as_view(template_name="users/register.html"), name="register"),
    path('email_confirm/<str:token>/', email_verification, name='email_confirm'),
    path('reset_password/', reset_password, name='reset_password'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    avatar = models.ImageField(upload_to='media/avatars/%Y/%m', blank=True, null=True)
    phone = models.CharField(max_length=35, verbose_name='Телефон')
    country = models.CharField(max_length=50, verbose_name='Страна', blank=True, null=True)

    token = models.CharField(max_length=100, verbose_name='Токен', blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователи'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from catalog.forms import StyleFormMixin
from django.contrib.auth.forms import UserCreationForm,  UserChangeForm, PasswordChangeForm
from django import forms
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

users/views.py
import random
import string
import secrets
from django.views.generic import CreateView, UpdateView
from django.urls import reverse_lazy, reverse
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from django.core.mail import send_mail
from config.settings import EMAIL_HOST_USER
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.hashers import make_password
from django.contrib import messages


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/email_confirm/{token}'
        send_mail(
            subject='Подтверждение почты',
            message=f'Привет, перейди по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def generate_random_password(length=8):
    """Generate a random password."""
    characters = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(characters) for _ in range(length))


def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = generate_random_password()
            user.password = make_password(new_password)  # Hash the new password
            user.save()

            # Send email with the new password
            send_mail(
                subject='Ваш новый пароль',
                message=f'Ваш новый пароль: {new_password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[email],
            )

            messages.success(request, 'Новый пароль отправлен на ваш адрес электронной почты.')
            return redirect('users:login')  # Redirect to login page after successful reset

        except User.DoesNotExist:
            messages.error(request, 'Пользователь с таким адресом электронной почты не найден.')

    return render(request, 'users/reset_password.html')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Войти
                        </button>

                        <div class="card-footer">
                            <a href="{% url 'users:reset_password' %}" class="ms-2 mb-2">Забыл пароль?</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Зарегистрироваться
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

users/templates/users/reset_password.html
{% extends 'catalog/home.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-4">
            <div class="card">

                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>

                <div class="card-body">
                    {% csrf_token %}
                    <label for="email">Введите ваш email:</label>
                    <input type="email" id="email" name="email" required>
                    <button type="submit">Восстановить пароль</button>


                    {% if messages %}
                    {% for message in messages %}
                    <div>{{ message }}</div>
                    {% endfor %}
                    {% endif %}
                </div>

                <div class="card-footer"></div>

            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}