blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreatView, BlogUpdateView, BlogDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', BlogListView.as_view(), name='blog_list'),
    path('blogs/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blogs/create/', BlogCreatView.as_view(), name='blog_create'),
    path('blogs/<int:pk>/update', BlogUpdateView.as_view(), name='update'),
    path('blogs/<int:pk>/delete', BlogDeleteView.as_view(), name='delete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (ProductDetailView, ContactPageView, HomePageView,
                           ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, CategoryListView)
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('catalog/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('contacts/', ContactPageView.as_view(), name='contacts'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete', ProductDeleteView.as_view(), name='product_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
    path('', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from users.models import User

NULLABLE = {"blank": True, "null": True}


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование категории"
    )
    description = models.TextField(
        verbose_name="Описание категории"
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование продукта"
    )
    description = models.TextField(
        verbose_name="Описание продукта"
    )
    image = models.ImageField(
        upload_to="images/",
        blank=True,
        null=True,
        verbose_name="Фото"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        related_name="products",
        blank=True,
        null=True,
    )
    price = models.IntegerField(verbose_name="Цена за покупку")
    created_at = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name="Дата создания(записи в БД)"
    )
    updated_at = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name="Дата последнего изменения(записи в БД)"
    )
    owner = models.ForeignKey(User, verbose_name="Владелец",
                              on_delete=models.SET_NULL, **NULLABLE)

    is_active = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "-created_at"]
        permissions = [
            ("can_edit_is_active", "Can edit is_active"),
            ("can_edit_description", "Can edit description"),
            ("can_edit_category", "Can edit category")
        ]

    def __str__(self):
        return self.name


class Version(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="название версии"
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name="продукт",
        related_name="version"
    )
    version_number = models.PositiveIntegerField(verbose_name="Версия")
    is_current = models.BooleanField(blank=True, null=True, verbose_name='текущая версия')

    def __str__(self):
        return f'Продукт - {self.product}, версия - {self.name}'

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django import forms
from django.forms import ModelForm

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        exclude = ['owner']

    stop_list = ['казино', 'криптовалюта', 'крипта', 'биржа',
                 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        for stop in self.stop_list:
            if stop in cleaned_data:
                raise forms.ValidationError('Вы пытались создать запрещенный продукт')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        for stop in self.stop_list:
            if stop in cleaned_data:
                raise forms.ValidationError('Вы пытались создать запрещенный продукт')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        exclude = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        product = cleaned_data.get('product')  # Получаем продукты из данных
        is_current = cleaned_data.get('is_current')  # Получаем статус активного

        if product and is_current:  # Проверьте, установлен ли продукт и активна ли эта версия
            # Проверьте наличие других активных версий
            active_versions = Version.objects.filter(product=product, is_current=True).exclude(pk=self.instance.pk)
            if active_versions.exists():
                raise forms.ValidationError(
                    'Ошибка: Для этого продукта уже существует активная версия. Пожалуйста, выберите только одну активную версию.')

        return cleaned_data


class ProductModeratorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Product
        fields = ('is_active', 'description', 'category')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.forms import inlineformset_factory
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from django.urls import reverse_lazy, reverse
from django.core.exceptions import PermissionDenied

from catalog.services import get_category_from_cache


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        products_with_versions = []
        # Пройдитесь по каждому продукту и извлеките его активную версию
        for product in self.object_list:
            active_version = product.version.filter(
                is_current=True).first()  # Используйте "version" вместо "version_set"
            products_with_versions.append({
                'product': product,
                'active_version': active_version
            })
        context_data['products_with_versions'] = products_with_versions
        return context_data

    def get_queryset(self):
        key = "product_list"
        return get_category_from_cache(Product, key)


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if form.is_valid() and formset.is_valid():
            self.object = form.save(commit=False)  # пока не сохраняем данные в базе
            self.object.owner = self.request.user  # привязываем текущего пользователя к продукту
            self.object.save()  # сохраняем данные в базе

            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data
    
    def form_valid(self, form):
        formset = self.get_context_data()['formset']

        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return ProductForm
        if (user.has_perm('catalog.can_edit_is_active') and user.has_perm('catalog.can_edit_description')
                and user.has_perm('catalog.can_edit_category')):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(DeleteView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"

    model = Product
    success_url = reverse_lazy('catalog:product_list')


class HomePageView(TemplateView):
    template_name = 'catalog/home.html'


class ContactPageView(TemplateView):
    template_name = 'catalog/contacts.html'


class CategoryListView(ListView):
    model = Category

    def get_queryset(self):
        key = "category_list"
        return get_category_from_cache(Category, key)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js'%}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'catalog/includes/inc_menu.html' %}
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                <h1 class="display-4">Всё для всех</h1>
                <p class="lead">Всё для всех - это отличный магазин, здесь много интересного по интересным ценам</p>
            </div>
        </div>
    </section>
    {% block content %}
    {% endblock %}
</main>
<div class="container">
    <div class="row text-start">
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Все для всех
                    <small class="d-block mb-3 text-muted">&copy; 2024</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Навигация по сайту</h5>
                    <ul class="list-unstyled text-small">
                        <li><a href="{% url 'catalog:home'%}" class="text-black">Главная</a></li>
                        <li><a href="{% url 'catalog:product_list'%}" class="text-black">Все продукты</a></li>
                        <li><a href="{% url 'blog:blog_list'%}" class="text-black">Блог</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">в разработке </a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-black" href="/contacts/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="mt-3 mb-3">
            <div class="col-lg-11">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                </div>
            </div>
            <div class="col-12">

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for category in category_list %}
                        <div class="col">
                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <p class="card-text">Название: {{ category.name }}</p>
                                    <p class="card-text">
                                        Описание: {{ category.description | truncatechars:100 }} </p>
                                    <div class="d-flex justify-content-between align-items-center">


                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>123-123-123 12</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Россия, г. Владимир</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


<div class="container">
    <div class="row">

        <div class="col-9">
            <div class="card col-6">

                <div class="card-header">
                    <h5 class="my-0 font-weight-normal">Оставьте имя и Email, мы с вами свяжемся</h5>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row mb-4">
                            <label for="name" class="form-label">Имя</label>
                            <input type="text" class="form-control" name="name" id="name">
                        </div>
                        <div class="row mt-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" name="email" id="email">
                        </div>
                        <button type="submit" class="mt-4 form-control" >Отправить</button>


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content%}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить продукт "{{object.name}}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a class="btn btn-warning" href="{% url 'catalog:product_list'%}">Отмена</a>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="mt-3 mb-3">
            <div class="col-lg-11">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    {% if user.is_authenticated %}
                        <div class="col-12">
                        <a class="btn btn-outline-primary mb-5" href="{% url 'catalog:product_create' %}">Добавить
                            продукт</a>
                    {% endif %}
                    </div>
                </div>
                <div class="col-12">

                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                        {% for product in products_with_versions %}
                            <div class="col">
                                <div class="card shadow-sm">
                                    <img src="{{ product.product.image  | media_filter }}" class="card-img-top"
                                         style="height: 200px; width: auto; object-fit: contain;">
                                    {% if product.active_version %}
                                        <p class="m-lg-3"><strong>Текущая
                                            версия:</strong> {{ product.active_version.name }}</p>
                                    {% else %}
                                        <p class="m-lg-3"><strong>Текущая версия:</strong> Нет активной версии</p>
                                    {% endif %}
                                    <div class="card-body">
                                        <p class="card-text">Название: {{ product.product.name }}</p>
                                        <p class="card-text">
                                            Описание: {{ product.product.description | truncatechars:100 }} </p>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group">
                                                <a class="btn btn-primary"
                                                   href="{% url 'catalog:product_detail' product.product.pk %}"
                                                   role="button">Посмотреть товар</a>
                                                {% if user.is_authenticated%}
                                                    <div class="btn-group">
                                                    {% if perms.catalog.can_edit_is_active and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == product.product.owner %}


                                                    <a class="btn btn-warning"
                                                       href="{% url 'catalog:product_update' product.product.pk %}"
                                                       role="button">Изменить</a>
                                                        {% endif %}
                                                    {% if product.product.owner == user or user.is_superuser %}
                                                    <a class="btn btn-danger"
                                                       href="{% url 'catalog:product_delete' product.product.pk %}"
                                                       role="button">удалить</a>
                                                        {% endif %}

                                                    </div>
                                                {% endif %}
                                        </div>

                                    </div>
                                </div>
                            </div>
                            </div>
                        {% endfor %}
                </div>

            </div>
{% endblock %}